#!/bin/bash

## set Initial Login Username & uid
UNAME=$1
UNAMEID=$2

## set Group & gid
GNAME=myusers
GNAMEID=500

## Disable text passwords
#sed -i.org -e "s/PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
#service sshd restart

## Change to Japanese locale
#
#

## Change to JST time zone
#
#

## Configure Linux Firewalld
#
#

## Install basic tools
#yum update -y
#yum install -y git tree cifs-utils zsh telnet lsof

## Enable EPEL Package
#rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

## Create Group
groupadd -g ${GNAMEID} ${GNAME}

## Create User
useradd -u ${UNAMEID} -g ${GNAMEID} -d /home/${UNAME} ${UNAME}
passwd -d ${UNAME}
mkdir -p /home/${UNAME}/.ssh
chmod 755 /home/${UNAME}/.ssh
chown ${UNAME}:myusers /home/${UNAME}/.ssh
cp -ip ~/.ssh/authorized_keys /home/${UNAME}/.ssh/.
chmod 600 /home/${UNAME}/.ssh/authorized_keys
chown ${UNAME}:myusers /home/${UNAME}/.ssh/authorized_keys

## Edit sudoers
echo "" >> /etc/sudoers
echo "## Allow ${GNAME} group to run any commands anywhere" >> /etc/sudoers
echo "%myusers ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
