#!/bin/bash

## set Initial Login Username & uid
UNAME=centos
UNAMEID=1009

## set Group & gid
GNAME=myusers
GNAMEID=500

LOGFILE=/tmp/postscript.log

## Disable text passwords
sed -i.org -e "s/PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config >> ${LOGFILE}
service sshd restart >> ${LOGFILE}

## Change to Japanese locale
#
#

## Change to JST time zone
#
#

## Configure Linux Firewalldyum install -y firewalld
yum install -y firewalld >> ${LOGFILE}
systemctl enable firewalld.service >> ${LOGFILE}
systemctl start  firewalld.service >> ${LOGFILE}
firewall-cmd             --change-interface=eth0 --zone=trusted >> ${LOGFILE}
firewall-cmd --permanent --change-interface=eth0 --zone=trusted >> ${LOGFILE}
firewall-cmd             --change-interface=eth1 --zone=block >> ${LOGFILE}
firewall-cmd --permanent --change-interface=eth1 --zone=block >> ${LOGFILE}

## Install basic tools
#yum update -y
#yum install -y git tree cifs-utils zsh telnet lsof
yum install -y zip unzip >> ${LOGFILE}

## Enable EPEL Package
#rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

## Create Group
groupadd -g ${GNAMEID} ${GNAME} >> ${LOGFILE}

## Create User
useradd -u ${UNAMEID} -g ${GNAMEID} -d /home/${UNAME} ${UNAME} >> ${LOGFILE}
passwd -d ${UNAME} >> ${LOGFILE}
mkdir -p /home/${UNAME}/.ssh >> ${LOGFILE}
chmod 755 /home/${UNAME}/.ssh >> ${LOGFILE}
chown ${UNAME}:myusers /home/${UNAME}/.ssh >> ${LOGFILE}
cp -ip ~/.ssh/authorized_keys /home/${UNAME}/.ssh/. >> ${LOGFILE}
chmod 600 /home/${UNAME}/.ssh/authorized_keys >> ${LOGFILE}
chown ${UNAME}:myusers /home/${UNAME}/.ssh/authorized_keys >> ${LOGFILE}

## Edit sudoers
echo "" >> /etc/sudoers
echo "## Allow ${GNAME} group to run any commands anywhere" >> /etc/sudoers
echo "%myusers ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
