#!/bin/bash

## set Initial Login Username & uid
UNAME=centos
UNAMEID=1009

## set Group & gid
GNAME=myusers
GNAMEID=500

## Disable text passwords
sed -i.org -e "s/PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
service sshd restart

## Change to Japanese locale
#
#

## Change to JST time zone
#
#

## Configure Linux Firewalldyum install -y firewalld
yum install -y firewalld
systemctl enable firewalld.service
systemctl start  firewalld.service
firewall-cmd             --change-interface=eth0 --zone=trusted
firewall-cmd --permanent --change-interface=eth0 --zone=trusted
firewall-cmd             --change-interface=eth1 --zone=block
firewall-cmd --permanent --change-interface=eth1 --zone=block

## Install basic tools
#yum update -y
#yum install -y git tree cifs-utils zsh telnet lsof
yum install -y zip unzip git tree

## Enable EPEL Package
#rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

## Create Group
groupadd -g ${GNAMEID} ${GNAME}

## Create User
useradd -u ${UNAMEID} -g ${GNAMEID} -d /home/${UNAME} ${UNAME}
## passwd -d ${UNAME}
mkdir -p /home/${UNAME}/.ssh
chmod 755 /home/${UNAME}/.ssh
chown ${UNAME}:myusers /home/${UNAME}/.ssh
cp -ip ~/.ssh/authorized_keys /home/${UNAME}/.ssh/.
chmod 600 /home/${UNAME}/.ssh/authorized_keys
chown ${UNAME}:myusers /home/${UNAME}/.ssh/authorized_keys

## monkey patching
groupadd -g 501 myusers2
useradd -u 1010 -g 501 -d /home/kazx kazx
passwd -d kazx
mkdir -p /home/kazx/.ssh
chmod 755 /home/kazx/.ssh
chown kazx:myusers2 /home/kazx/.ssh
cp -ip ~/.ssh/authorized_keys /home/kazx/.ssh/.
chmod 600 /home/kazx/.ssh/authorized_keys
chown kazx:myusers /home/kazx/.ssh/authorized_keys
useradd -u 1011 -g 501 -d /home/kentarok kentarok
passwd -d kentarok
mkdir -p /home/kentarok/.ssh
chmod 755 /home/kentarok/.ssh
chown kentarok:myusers2 /home/kentarok/.ssh
cp -ip ~/.ssh/authorized_keys /home/kentarok/.ssh/.
chmod 600 /home/kentarok/.ssh/authorized_keys
chown kentarok:myusers /home/kentarok/.ssh/authorized_keys

## Edit sudoers
echo "" >> /etc/sudoers
echo "## Allow myuser2 group to run any commands anywhere" >> /etc/sudoers
echo "%myusers2 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

## Chef DK install
rpm -Uvh https://packages.chef.io/files/stable/chefdk/2.1.11/el/7/chefdk-2.1.11-1.el7.x86_64.rpm
